name: testing
on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build-docker-image:
    runs-on: ubuntu-22.04
    env:
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      DOCKER_HUB_USER: apkwan

    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: docker login
        run: |
          echo $DOCKER_HUB_TOKEN > password.txt
          cat password.txt | docker login --username apkwan --password-stdin
      - name: build image
        run: |
          docker image build -t apkwan/fastapi-demo:latest .
      - name: push image
        run: |
          docker image push apkwan/fastapi-demo:latest
