name: testing
on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build-docker-image:
    runs-on: ubuntu-22.04
    env:
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      DOCKER_HUB_USER: apkwan

    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: build docker image
        uses: ./.github/actions/docker
        with:
          docker_hub_user: ${{ secrets.DOCKER_HUB_USER }}
          docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}
          image_name: fastapi-mongo-demo:latest
